// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEKStmOulETrNO9PkIiWPX0M85Dhfq0wQ',
    appId: '1:820391007726:web:91fd707cb882213c51aaff',
    messagingSenderId: '820391007726',
    projectId: 'les-delices-artisane',
    authDomain: 'les-delices-artisane.firebaseapp.com',
    storageBucket: 'les-delices-artisane.firebasestorage.app',
    measurementId: 'G-34YJMRLSJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMtsWU9ofjXbgoUOJii4KbPGseBQuvEM',
    appId: '1:820391007726:android:9e577dca708ba18051aaff',
    messagingSenderId: '820391007726',
    projectId: 'les-delices-artisane',
    storageBucket: 'les-delices-artisane.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfiLKJ_Ibqb3Jq6n_wbOaq4IfyCKxnL2Q',
    appId: '1:820391007726:ios:6ff1717b31cf0b5651aaff',
    messagingSenderId: '820391007726',
    projectId: 'les-delices-artisane',
    storageBucket: 'les-delices-artisane.firebasestorage.app',
    iosClientId: '820391007726-f6t80hr218lc1t8vkeg7slieek8kooec.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesDelicesArtisane',
  );
}
